# ---- Site metadata ----
title: Hidas Hurston
description: FPGA · HFT · Systems Engineer
url: "https://Hurstonthan.github.io"      # ← change to your repo URL
baseurl: ""                               # keep empty for username.github.io

# ---- Theme ----
theme: minima

# ---- Minima social icons ----
minima:
  social_links:
    email: trithan511@gmail.com
    github:   https://github.com/Hurstonthan          # your GitHub username
    linkedin: https://www.linkedin.com/in/tri-than/        # LinkedIn “handle” (the part after /in/)
    # twitter:  your_twitter       # add others if you want

# ---- Plugins (optional) ----
plugins:
  - jekyll-feed                    # Atom/RSS feed
  - jekyll-sitemap                 # XML sitemap

# ---- Sass: allow extra.scss to compile ----
sass:
  sass_dir: assets/css
  load_paths:
    - assets/css

# ---- Include our custom <link> tag in <head> ----
include:
  - _includes/custom-head.html
